# Lab 1: Introduction to OpenCV

The goal of this first lab is to present a small introduction to image processing using OpenCV. In each section, you can find:
* a small example - analyse the code and try it
* some exercises

In [1]:
# Requirements for this tutorial
! pip install opencv-python
! pip install numpy

In [2]:
# If you prefer, you can convert this notebook to a Python script by uncommenting the following command
# ! pip install nbconvert
# ! jupyter nbconvert --to script 01-introduction.ipynb

In [3]:
import cv2
import numpy as np
import os

dataDir = './data'

### 1. Images – read, write and display; ROIs

In [4]:
# Opening an image
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

# Showing the image
cv2.imshow("ml.jpg", img)

# Waiting for user to press a key to close the image
cv2.waitKey(0)

# Close the window after user pressed a key
cv2.destroyWindow("ml.jpg")

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

In [5]:
# Check image size
h, w, c = img.shape
print(f'height: {h}')
print(f'width: {w}')
print(f'channels: {c}')

height: 380
width: 308
channels: 3


In [6]:
# Saving image in bmp format
cv2.imwrite('ml_new.bmp', img)

True

Exercise 1.1 - Read any other color image from a file, show the mouse cursor over the image, and the coordinates and RGB components of the pixel under the cursor. When the user clicks on the mouse, let him modify the RGB components of the selected pixel.

In [7]:
# Opening an image
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

# Define the function to paint the coordinates

def paint_coordinates(event, x, y, flags, params):
    if event == cv2.EVENT_MOUSEMOVE:
        print(f'x: {x}, y: {y}')
        print(f'RGB: {img[y] [x]}')

    # Modify color of pixel when clicking on it
    if event == cv2.EVENT_LBUTTONDOWN:
        img[y][x] = [255, 0, 0]

# Define window
cv2.namedWindow("image_window", cv2.WINDOW_NORMAL)

cv2.setMouseCallback("image_window", paint_coordinates)

while(True):
    cv2.imshow("image_window", img)
    if cv2.waitKey(2) == ord('q'):
        break

# Show the image
cv2.imshow("image_window", img)

# Waiting for user to press a key to close the image
cv2.waitKey(1)

# Close the window after user pressed a key
cv2.destroyWindow("image_window")

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

x: 293, y: 375
RGB: [255 255 255]
x: 289, y: 359
RGB: [255 255 255]
x: 284, y: 350
RGB: [255 255 255]
x: 281, y: 342
RGB: [255 255 255]
x: 279, y: 337
RGB: [255 255 255]
x: 277, y: 332
RGB: [255 255 255]
x: 277, y: 331
RGB: [255 255 255]
x: 277, y: 329
RGB: [255 255 255]
x: 279, y: 327
RGB: [255 255 255]
x: 279, y: 326
RGB: [255 255 255]
x: 281, y: 324
RGB: [255 255 255]
x: 279, y: 326
RGB: [255 255 255]
x: 279, y: 326
RGB: [255 255 255]
x: 279, y: 326
RGB: [255 255 255]


Exercise 1.2 - Allow the user to select a region of interest (ROI) in the image, by clicking on two points that identify two opposite corners of the selected ROI, and save the ROI into another file.

In [9]:
# Open image
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

# Select a region of interest, using selectROI
r = cv2.selectROI(img)

cv2.destroyAllWindows()

# Crop image

x = int(r[0])
y = int(r[1])
w = int(r[2])
h = int(r[3])

img_roi = img[y:y+h, x:x+w]

cv2.imshow("Image", img_roi)

# Save ROI into another file
cv2.imwrite("ml_roi.jpg", img_roi)

# Waiting for user to press a key to close the image
cv2.waitKey(0)

# Close the window after user pressed a key
cv2.destroyWindow("Image")

Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

### 2. Images – representation, grayscale and color, color spaces

In [10]:
# Create a white image
m = np.ones((100,200,1), np.uint8)

# Change the intensity to 100
m = m * 100

# Display the image
cv2.imshow('Grayscale image', m)
cv2.waitKey(0)
cv2.destroyWindow('Grayscale image')

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

In [11]:
# Draw a line with thickness of 5 px
cv2.line(m, (0,0), (200,100), 255, 5)
cv2.line(m, (200, 0), (0, 100), 255, 5)
cv2.imshow('Grayscale image with diagonals', m)
cv2.waitKey(0)
cv2.destroyWindow('Grayscale image with diagonals')

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

Exercise 2.1 - Create a color image with 100(lines)x200(columns) pixels with yellow color; draw the two diagonals of the image, one in red color, the other in blue color. Display the image.

In [12]:
# Create a yellow image
m = np.ones((100,200,3), np.uint8)

# Change the colour to yellow
m[:,:,0] = 0
m[:,:,1:] = 255

# Draw a red line with thickness of 5 px
cv2.line(m, (0,0), (200,100), (0, 0, 255), 5)

# Draw a blue line with thickness of 5 px
cv2.line(m, (200, 0), (0, 100), (255, 0, 0), 5)

# Display the image
cv2.imshow('Colour image with diagonals', m)
cv2.waitKey(0)
cv2.destroyWindow('Colour image with diagonals')

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

Exercise 2.2 - Read any color image, in RGB format, display it in one window, convert it to grayscale, display the grayscale image in another window and save the grayscale image to a different file

In [13]:
# Read an image
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

# Display the image in one window
cv2.imshow('Image', img)

# Wait for a key to be pressed
cv2.waitKey(0)

# Close all windows
cv2.destroyAllWindows()

# Convert the image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Display the grayscale image in another window
cv2.imshow('Grayscale image', gray)

# Wait for a key to be pressed
cv2.waitKey(0)

# Save the grayscale image
cv2.imwrite('ml_gray.jpg', gray)

# Close all windows
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

Exercise 2.3 - Split the 3 RGB channels and show each channel in a separate window. Add a constant value to one of the channels, merge the channels into a new color image and show the resulting image.

In [14]:
# Opening an image
img = cv2.imread(os.path.join(dataDir, "ml.jpg"))

r = img.copy()
r[:, :, 0] = r[:, :, 1] = 0

g = img.copy()
g[:, :, 0] = g[:, :, 2] = 0

b = img.copy()
b[:, :, 1] = b[:, :, 2] = 0

# Display each channel in a different window
cv2.imshow("red", r)
cv2.imshow("green", g)
cv2.imshow("blue", b)

cv2.waitKey(0)
cv2.destroyAllWindows()

b,g,r = cv2.split(img)

# Add a constant value to the red channel
r_modified = r + 10

# Clip the values to be between 0 and 255
r_modified = np.clip(r_modified, 0, 255).astype(np.uint8)

# Merge the channels
new_img = cv2.merge((b, g, r_modified))

# Display the new image
cv2.imshow('Image', new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

Exercise 2.4 - Convert the image to HSV, split the 3 HSV channels and show each channel in a separate window. Add a constant value to saturation channel, merge the channels into a new color image and show the resulting image.

In [15]:
# Read an image
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

# Convert the image to HSV
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

# Split the converted image into its channels
h, s, v = cv2.split(hsv)

# Display the channels in different windows
cv2.imshow('Hue', h)
cv2.imshow('Saturation', s)
cv2.imshow('Value', v)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Add a constant value to the saturation channel
s_modified = s + 10

# Clip the values to be between 0 and 255
s_modified = np.clip(s_modified, 0, 255).astype(np.uint8)

# Merge the channels
new_hsv = cv2.merge((h, s_modified, v))

# Display the new image
new_img = cv2.cvtColor(new_hsv, cv2.COLOR_HSV2BGR)
cv2.imshow('Image', new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

### 3. Video – acquisition and simple processing

In [16]:
# Define a VideoCapture Object
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()

frame_nr = 0
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # If frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break

    # Display the resulting frame
    cv2.imshow('webcam', frame)

    # Wait for user to press s to save frame
    if cv2.waitKey(1) == ord('s'):
        frame_name = 'frame' + str(frame_nr) + '.png'
        cv2.imwrite(frame_name, frame)
        cv2.imshow("Saved frame: " + frame_name, frame)
        cv2.waitKey(0)
        cv2.destroyWindow("Saved frame: " + frame_name)

    # Wait for user to press q to quit
    if cv2.waitKey(1) == ord('q'):
        break

    frame_nr += 1

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

Exercise 3.1 - Using the previous example as the baseline, implement a script that acquires the video from the webcam, converts it to grayscale, and shows the frames in binary format (i.e. the intensity of each pixel is 0 or 255); use a threshold value of 128.

In [21]:
import cv2

# Define a VideoCapture Object
cap = cv2.VideoCapture(0)

# Check if camera opened successfully
if not cap.isOpened():
    print("Error opening video stream or file")

frame_nr = 0
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    # If frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break

    # Convert it to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Shows the frames in binary format, using a threshold of 128
    _, binary = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY)

    # Display the resulting frame
    cv2.imshow('webcam', binary)

    # Wait for user to press s to save frame
    key = cv2.waitKey(1)
    if key == ord('s'):
        frame_name = 'frame' + str(frame_nr) + '.png'
        cv2.imwrite(frame_name, binary)
        print("Frame saved as:", frame_name)

    # Wait for user to press q to quit
    if key == ord('q'):
        break

    frame_nr += 1

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

Frame saved as: frame80.png
Frame saved as: frame145.png
Frame saved as: frame208.png
Frame saved as: frame256.png
Frame saved as: frame328.png


Exercise 3.2 - Implement a simple detection/tracking algorithm for colored objects, using the following steps:
1) take each frame of the video;
2) convert from BGR to HSV color-space;
3) threshold the HSV image for a range of color values (creating a binary image);
4) extract the objects of the selected range (with a bitwise AND operation, using as operands the original and the binary image).

In [28]:
# Define a VideoCapture Object
cap = cv2.VideoCapture(0)

# Check if camera opened successfully
if not cap.isOpened():
    print("Error opening video stream or file")

frame_nr = 0
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    # If frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break

    # Convert it to HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # Treshold the frame to get only blue, creating a binary image
    lower_blue = np.array([90, 50, 50])  # Adjusted lower bound for blue
    upper_blue = np.array([150, 255, 255])  # Adjusted upper bound for blue
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    # Extract the blue objects from the frame, using bitwise AND with the mask 
    # and the original frame
    blue_objects = cv2.bitwise_and(frame, frame, mask=mask)

    # Display the blue objects
    cv2.imshow('webcam', blue_objects)

    # Wait for user to press s to save frame
    key = cv2.waitKey(1)
    if key == ord('s'):
        frame_name = 'frame' + str(frame_nr) + '.png'
        cv2.imwrite(frame_name, blue_objects)
        print("Frame saved as:", blue_objects)

    # Wait for user to press q to quit
    if key == ord('q'):
        break

    frame_nr += 1

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread (0x2bd2c20).
Cannot move to target thread (0x272a4c0)

QObject::moveToThread: Current thread (0x272a4c0) is not the object's thread

Frame saved as: [[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [141  94  38]
  [142  96  38]
  [140  94  35]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [142  95  39]
  [141  95  36]
  [141  95  36]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [144  94  41]
  [141  94  38]
  [141  94  38]]]
